Loan.Cars/Controllers/BookingController.cs
using Loan.Cars.Business;
using Loan.Cars.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Loan.Cars.Controllers
{
    public class BookingController : Controller
    {
        #region initialisation

        private BookingBusiness bookingBusiness { get; set; } 
        public BookingController()
        {
            bookingBusiness = new BookingBusiness(Models.ApplicationDbContext.Create()); 
        }

        #endregion

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Details(int id)
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(BookingViewModel vm)
        {
            try
            {
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Edit(int id)
        {
            return View();
        }

        [HttpPost]
        public ActionResult Edit(BookingViewModel vm)
        {
            return RedirectToAction("Index");
            //return View();
        }

        public ActionResult Delete(int id)
        {
            return RedirectToAction("Index");
            //return View();
        }

        public ActionResult Cancel()
        {
            return RedirectToAction("Index");
            //return View();
        }
    }
}

Loan.Cars/Controllers/VehiculeController.cs
using Loan.Cars.Business;
using Loan.Cars.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Loan.Cars.Controllers
{
    public class VehiculeController : Controller
    {
        #region initialisation

        private VehiculeBusiness vehiculeBusiness { get; set; }
        private ModeleVehiculeBusiness modeleBusiness { get; set; }
        private MarqueVehiculeBusiness marqueBusiness { get; set; }
        private CategorieVehiculeBusiness categorieBusiness { get; set; }
        private AgenceBusiness agenceBusiness { get; set; }
        
        public VehiculeController()  
        {
            vehiculeBusiness = new VehiculeBusiness(ApplicationDbContext.Create());
            modeleBusiness = new ModeleVehiculeBusiness(ApplicationDbContext.Create());
            marqueBusiness = new MarqueVehiculeBusiness(ApplicationDbContext.Create());
            categorieBusiness = new CategorieVehiculeBusiness(ApplicationDbContext.Create());
            agenceBusiness = new AgenceBusiness(ApplicationDbContext.Create());
        }

        #endregion

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Details(int id)
        {
            return View();
        }

        public ActionResult Create()
        {
            var marques = marqueBusiness.GetMarqueVehicules().Select(x => new SelectListItem { Text = x.Name, Value = x.Id.ToString() });
            int marqueId = int.Parse(marques.FirstOrDefault().Value);
            var modeles = modeleBusiness.GetModeleVehiculeByMarqueId(marqueId);
            var categories = modeles.Select(x => new SelectListItem { Text = x.Categorie.Name, Value = x.Categorie.Id.ToString() });

            ViewBag.Marques = marques;
            ViewBag.Modeles = modeles.Select(x => new SelectListItem { Text = x.Name, Value = x.Id.ToString() });
            ViewBag.Categories = modeles.Select(x => new SelectListItem { Text = x.Categorie.Name, Value = x.Categorie.Id.ToString() });
            ViewBag.Agences = agenceBusiness.GetAgences().Select(x => new SelectListItem { Text = x.Name, Value = x.Id.ToString() });

            return View();
        }

        [HttpPost]
        public ActionResult Create(VehiculeViewModel vm)
        {
            try
            {
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Edit(int id)
        {
            return View();
        }

        [HttpPost]
        public ActionResult Edit(VehiculeViewModel vm)
        {
            try
            {
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Delete(int id)
        {
            return RedirectToAction("Index");
            //return View();
        }

        public JsonResult GetDropDownDataModele(string id)
        {
            var modeles = modeleBusiness.GetModeleVehiculeByMarqueId(int.Parse(id));
            return Json(modeles.Select(x => new { Id = x.Id, Name = x.Name }), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetDropDownDataCategorie(string id)
        { 
            var categories = categorieBusiness.GetCategorieVehiculeByModelId(int.Parse(id));
            return Json(categories.Select(x => new { Id = x.Id, Name = x.Name }), JsonRequestBehavior.AllowGet);
        }
    }
}

Loan.Cars/Views/Shared/_Datepicker.cshtml
@model System.String


<div class="fuelux-datepicker">
    <div class="input-group">
        <input class="form-control" type="text" @Html.Raw(@Model) />
        <div class="input-group-btn">
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                <span class="glyphicon glyphicon-calendar"></span>
                <span class="sr-only">Toggle Calendar</span>
            </button>
            <div class="dropdown-menu dropdown-menu-right datepicker-calendar-wrapper" role="menu">
                <div class="datepicker-calendar">
                    <div class="datepicker-calendar-header">
                        <button type="button" class="prev"><span class="glyphicon glyphicon-chevron-left"></span><span class="sr-only">Previous Month</span></button>
                        <button type="button" class="next"><span class="glyphicon glyphicon-chevron-right"></span><span class="sr-only">Next Month</span></button>
                        <button type="button" class="title">
                            <span class="month">
                                <span data-month="0">January</span>
                                <span data-month="1">February</span>
                                <span data-month="2">March</span>
                                <span data-month="3">April</span>
                                <span data-month="4">May</span>
                                <span data-month="5">June</span>
                                <span data-month="6">July</span>
                                <span data-month="7">August</span>
                                <span data-month="8">September</span>
                                <span data-month="9">October</span>
                                <span data-month="10">November</span>
                                <span data-month="11">December</span>
                            </span> <span class="year"></span>
                        </button>
                    </div>
                    <table class="datepicker-calendar-days">
                        <thead>
                            <tr>
                                <th>Su</th>
                                <th>Mo</th>
                                <th>Tu</th>
                                <th>We</th>
                                <th>Th</th>
                                <th>Fr</th>
                                <th>Sa</th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                    <div class="datepicker-calendar-footer">
                        <button type="button" class="datepicker-today">Today</button>
                    </div>
                </div>
                <div class="datepicker-wheels" aria-hidden="true">
                    <div class="datepicker-wheels-month">
                        <h2 class="header">Month</h2>
                        <ul>
                            <li data-month="0"><button type="button">Jan</button></li>
                            <li data-month="1"><button type="button">Feb</button></li>
                            <li data-month="2"><button type="button">Mar</button></li>
                            <li data-month="3"><button type="button">Apr</button></li>
                            <li data-month="4"><button type="button">May</button></li>
                            <li data-month="5"><button type="button">Jun</button></li>
                            <li data-month="6"><button type="button">Jul</button></li>
                            <li data-month="7"><button type="button">Aug</button></li>
                            <li data-month="8"><button type="button">Sep</button></li>
                            <li data-month="9"><button type="button">Oct</button></li>
                            <li data-month="10"><button type="button">Nov</button></li>
                            <li data-month="11"><button type="button">Dec</button></li>
                        </ul>
                    </div>
                    <div class="datepicker-wheels-year">
                        <h2 class="header">Year</h2>
                        <ul></ul>
                    </div>
                    <div class="datepicker-wheels-footer clearfix">
                        <button type="button" class="btn datepicker-wheels-back"><span class="glyphicon glyphicon-arrow-left"></span><span class="sr-only">Return to Calendar</span></button>
                        <button type="button" class="btn datepicker-wheels-select">Select <span class="sr-only">Month and Year</span></button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Loan.Cars/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <script src="~/Scripts/jquery-1.8.3.min.js"></script>
    @*<script src="~/Scripts/jquery-1.12.4.min.js"></script>*@
    <script src="~/Scripts/jquery-ui.min.js"></script>
    <script src="~/Scripts/js/bootstrap-datetimepicker.min.js"></script>


    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/site.css")" rel="stylesheet">
    <link href="~/Content/css/bootstrap-datetimepicker.min.css" rel="stylesheet" />

    <title>@ViewBag.Title - Loan Cars</title>

</head>
<body>

    @Html.Partial("_PartialMenu")

    <div class="container body-content">

        @RenderBody()

        @Html.Partial("_PartialFooter")

    </div>

    @*<script src="~/Scripts/jquery-1.8.3.min.js"></script>*@
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/js/bootstrap-datetimepicker.min.js"></script>
    <script src="~/Scripts/js/locales/bootstrap-datetimepicker.fr.js"></script>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/css")
    @RenderSection("scripts", required: false)

    
</body>
</html>

Loan.Cars/Views/Shared/_PartialAdminMenu.cshtml
@if (User != null && User.Identity.IsAuthenticated && User.IsInRole("ADMIN"))
{
    <li>
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Administration <b class="caret"></b></a>
        <ul class="dropdown-menu multi-level">
            <li class="dropdown-submenu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Agences</a>
                <ul class="dropdown-menu">
                    <li><a href="@Url.Action("Create","Agence")">Créer une agence</a></li>
                    <li><a href="@Url.Action("Index","Agence")">Voir la liste des agences</a></li>
                </ul>
            </li>
            <li class="divider"></li>
            <li class="dropdown-submenu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Employées</a>
                <ul class="dropdown-menu">
                    <li><a href="@Url.Action("Create","Employee")">Créer un employée</a></li>
                    <li><a href="@Url.Action("Index","Employee")">Voir la liste des employées</a></li>
                </ul>
            </li>
            <li class="divider"></li>
            <li class="dropdown-submenu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Voitures</a>
                <ul class="dropdown-menu">
                    <li><a href="@Url.Action("Create","Vehicule")">Ajouter une voiture</a></li>
                    <li><a href="@Url.Action("Index","Vehicule")">Voir la liste des voiturex</a></li>
                </ul>
            </li>
        </ul>
    </li>
}

Loan.Cars/Views/Shared/_PartialFooter.cshtml
<hr />
<footer class="footer">
    <p> &copy; @DateTime.Now.Year - Loan Cars </p>
</footer>

Loan.Cars/Views/Shared/_PartialLogIn.cshtml
<ul class="nav navbar-nav navbar-right">

    <li>
        <a id="loginLink" href="@Url.Action("Login", "Account")">
            <i class="glyphicon glyphicon-log-in"></i>
            <span style="margin-left: 5px;">Connexion</span>
        </a>
    </li>

</ul>

Loan.Cars/Views/Shared/_PartialLogOff.cshtml
@if (User != null && User.Identity.IsAuthenticated)
{
    using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
    {
        @Html.AntiForgeryToken()
        <ul class="nav navbar-nav navbar-right">
            
            @Html.Partial("_PartialUserInfo")

            <li><a href="javascript:document.getElementById('logoutForm').submit()">
                    <i class="glyphicon glyphicon-log-out"></i>
                    <span>Déconnexion</span>
                </a>
            </li>
        </ul>
    }
}

Loan.Cars/Views/Shared/_PartialMenu.cshtml
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Accueil", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">

                @*<li>@Html.ActionLink("À propos de", "About", "Home")</li>*@

                @Html.Partial("_PartialUserMenu")

                @Html.Partial("_PartialAdminMenu")

            </ul>

            @Html.Partial("_LoginPartial")

        </div>
    </div>
</div>

Loan.Cars/Views/Shared/_PartialUserInfo.cshtml
@using Microsoft.AspNet.Identity

@if (User != null && @User.Identity.IsAuthenticated)
{
    <li>
        @Html.ActionLink((string)Session[User.Identity.GetUserId()], "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Gérer votre compte" })
    </li>
}

Loan.Cars/Views/Shared/_PartialUserMenu.cshtml
@*&& (User.IsInRole("ADMIN") || User.IsInRole("EMPLOYEE")))*@
@if (User != null && User.Identity.IsAuthenticated)  
{
    <li>
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Reservation <b class="caret"></b></a>
        <ul class="dropdown-menu multi-level">
            <li><a href="@Url.Action("Cancel","Booking")">Annuler une reservation</a></li>
            <li><a href="@Url.Action("Index","Booking")">Liste des reservations</a></li>
        </ul>
    </li>
}